jdbc.url=jdbc:mysql://db01.vprofile:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

jdbc.username=admin
jdbc.password=Admin@123

memcached.active.host=mc01.vprofile
memcached.active.port=11211

memcached.standBy.host=mc01.vprofile
memcached.standBy.port=11211

rabbitmq.address=rmq01.vprofile
rabbitmq.port=5672
rabbitmq.username=admin
rabbitmq.password=Admin@123456
